import type { Metadata } from "next";
import "./globals.css";
import CalendarAside from "@/components/calendarAside";
import NavBar from "@/components/navBar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='h-screen flex flex-col'>
        <NavBar />
        <CalendarAside />
        {children}
      </body>
    </html>
  );
}
